# # Generated by Django 4.2.23 on 2025-09-09 16:32

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('orders', '0001_initial'),
#     ]

#     operations = [
#     ]

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),  # previous migration
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='buyer',
            field=models.ForeignKey(
                default=1,  # temporary default, jekono existing user ID
                on_delete=models.CASCADE,
                related_name='reviews_given',
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
